version: "3"

services:
  web:
    container_name: react
    build:
      context: .
      dockerfile: ./apps/react-app/Dockerfile
    restart: always
    ports:
      - 5173:5173
    networks:
      - app_network
    volumes:
      - ./apps/react-app/src:/app/apps/react-app/src      

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    volumes:
      - ./apps/api/src:/app/apps/api/src      

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
